server:
  port: 8081
  
spring:
  application:
    name: auth-service
  
  datasource: 
    url: jdbc:postgresql://localhost:5432/frwkDb
    username : postgres
    password: root
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: krishCode@911218
  expiryinms: 1500000 
  
